### ISSUE TITLE
500 We have a problem... - org.bsoftware.ward.exceptions.CantGetPhysicalMemoryArrayException: null

### ISSUE THREAD

**Issue by LukasRada** [B-Software/Ward#24]
When settings name (odroid) and port to 4444 on intro screen, error page appeared.
![image](https://user-images.githubusercontent.com/7394177/86495478-d6c2bb00-bd79-11ea-8a72-3a9ec316414a.png)

The device is Odroid-HC2.
Here is info about HW.
[lshw.txt](https://github.com/B-Software/Ward/files/4871322/lshw.txt)

Can I do something to resolve the issue?

**Comment by Rudolf-Barbu** [comment]
Please try run application with administrative rights or/and install dmidecode this may help

**Comment by LukasRada** [comment]
I tried to run the *.jar file as root but with the exactly same result.
dmidecode doesn't support ARM devices.

Is it possible to run Ward on ARM device at all?

**Comment by Rudolf-Barbu** [comment]
It depends on, if OSHI supports arm. As i remember yes. I need more research to provide instructions for you.

**Comment by Bad3r** [comment]
Same error effects x86 Arch Linux `5.7.7-arch1-1`
I ran the jar file with `sudo` and I installed `dmidecode` and that didn't help

Error stack
```
2020-07-04 08:34:56.566  INFO 6420 --- [       Thread-3] o.s.boot.SpringApplication               : Starting application on Baph with PID 6420 (/home/vx/git/Ward/ward-1.5.3.jar started by root in /root)
2020-07-04 08:34:56.567  INFO 6420 --- [       Thread-3] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
2020-07-04 08:34:56.695  WARN 6420 --- [       Thread-3] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is java.lang.NumberFormatException: null
2020-07-04 08:34:56.697  INFO 6420 --- [       Thread-3] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-07-04 08:34:56.700 ERROR 6420 --- [       Thread-3] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is java.lang.NumberFormatException: null
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.bsoftware.ward.Ward.lambda$restart$0(Ward.java:62) [classes!/:1.5.3]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_252]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is java.lang.NumberFormatException: null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:210) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:179) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	... 9 common frames omitted
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542) ~[na:1.8.0_252]
	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_252]
	at org.bsoftware.ward.components.containers.ServletContainer.customize(ServletContainer.java:39) ~[classes!/:1.5.3]
	at org.bsoftware.ward.components.containers.ServletContainer.customize(ServletContainer.java:17) ~[classes!/:1.5.3]
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.lambda$postProcessBeforeInitialization$0(WebServerFactoryCustomizerBeanPostProcessor.java:72) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.util.LambdaSafe$Callbacks.lambda$null$0(LambdaSafe.java:287) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.util.LambdaSafe$LambdaSafeCallback.invoke(LambdaSafe.java:159) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.util.LambdaSafe$Callbacks.lambda$invoke$1(LambdaSafe.java:286) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_252]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082) ~[na:1.8.0_252]
	at org.springframework.boot.util.LambdaSafe$Callbacks.invoke(LambdaSafe.java:286) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:72) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:58) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	... 17 common frames omitted

Exception in thread "Thread-3" org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is java.lang.NumberFormatException: null
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.bsoftware.ward.Ward.lambda$restart$0(Ward.java:62)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is java.lang.NumberFormatException: null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:210)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:179)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153)
	... 9 more
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.bsoftware.ward.components.containers.ServletContainer.customize(ServletContainer.java:39)
	at org.bsoftware.ward.components.containers.ServletContainer.customize(ServletContainer.java:17)
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.lambda$postProcessBeforeInitialization$0(WebServerFactoryCustomizerBeanPostProcessor.java:72)
	at org.springframework.boot.util.LambdaSafe$Callbacks.lambda$null$0(LambdaSafe.java:287)
	at org.springframework.boot.util.LambdaSafe$LambdaSafeCallback.invoke(LambdaSafe.java:159)
	at org.springframework.boot.util.LambdaSafe$Callbacks.lambda$invoke$1(LambdaSafe.java:286)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
	at org.springframework.boot.util.LambdaSafe$Callbacks.invoke(LambdaSafe.java:286)
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:72)
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:58)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	... 17 more
```

**Comment by Rudolf-Barbu** [comment]
> Same error effects x86 Arch Linux `5.7.7-arch1-1`
> I ran the jar file with `sudo` and I installed `dmidecode` and that didn't help
> 
> Error stack
> 
> ```
> 2020-07-04 08:34:56.566  INFO 6420 --- [       Thread-3] o.s.boot.SpringApplication               : Starting application on Baph with PID 6420 (/home/vx/git/Ward/ward-1.5.3.jar started by root in /root)
> 2020-07-04 08:34:56.567  INFO 6420 --- [       Thread-3] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
> 2020-07-04 08:34:56.695  WARN 6420 --- [       Thread-3] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is java.lang.NumberFormatException: null
> 2020-07-04 08:34:56.697  INFO 6420 --- [       Thread-3] ConditionEvaluationReportLoggingListener :
> 
> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
> 2020-07-04 08:34:56.700 ERROR 6420 --- [       Thread-3] o.s.boot.SpringApplication               : Application run failed
> 
> org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is java.lang.NumberFormatException: null
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	at org.bsoftware.ward.Ward.lambda$restart$0(Ward.java:62) [classes!/:1.5.3]
> 	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_252]
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is java.lang.NumberFormatException: null
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:210) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:179) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	... 9 common frames omitted
> Caused by: java.lang.NumberFormatException: null
> 	at java.lang.Integer.parseInt(Integer.java:542) ~[na:1.8.0_252]
> 	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_252]
> 	at org.bsoftware.ward.components.containers.ServletContainer.customize(ServletContainer.java:39) ~[classes!/:1.5.3]
> 	at org.bsoftware.ward.components.containers.ServletContainer.customize(ServletContainer.java:17) ~[classes!/:1.5.3]
> 	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.lambda$postProcessBeforeInitialization$0(WebServerFactoryCustomizerBeanPostProcessor.java:72) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	at org.springframework.boot.util.LambdaSafe$Callbacks.lambda$null$0(LambdaSafe.java:287) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	at org.springframework.boot.util.LambdaSafe$LambdaSafeCallback.invoke(LambdaSafe.java:159) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	at org.springframework.boot.util.LambdaSafe$Callbacks.lambda$invoke$1(LambdaSafe.java:286) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_252]
> 	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082) ~[na:1.8.0_252]
> 	at org.springframework.boot.util.LambdaSafe$Callbacks.invoke(LambdaSafe.java:286) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:72) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:58) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
> 	... 17 common frames omitted
> 
> Exception in thread "Thread-3" org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is java.lang.NumberFormatException: null
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156)
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
> 	at org.bsoftware.ward.Ward.lambda$restart$0(Ward.java:62)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is java.lang.NumberFormatException: null
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:210)
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:179)
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153)
> 	... 9 more
> Caused by: java.lang.NumberFormatException: null
> 	at java.lang.Integer.parseInt(Integer.java:542)
> 	at java.lang.Integer.parseInt(Integer.java:615)
> 	at org.bsoftware.ward.components.containers.ServletContainer.customize(ServletContainer.java:39)
> 	at org.bsoftware.ward.components.containers.ServletContainer.customize(ServletContainer.java:17)
> 	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.lambda$postProcessBeforeInitialization$0(WebServerFactoryCustomizerBeanPostProcessor.java:72)
> 	at org.springframework.boot.util.LambdaSafe$Callbacks.lambda$null$0(LambdaSafe.java:287)
> 	at org.springframework.boot.util.LambdaSafe$LambdaSafeCallback.invoke(LambdaSafe.java:159)
> 	at org.springframework.boot.util.LambdaSafe$Callbacks.lambda$invoke$1(LambdaSafe.java:286)
> 	at java.util.ArrayList.forEach(ArrayList.java:1257)
> 	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
> 	at org.springframework.boot.util.LambdaSafe$Callbacks.invoke(LambdaSafe.java:286)
> 	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:72)
> 	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:58)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
> 	... 17 more
> ```

I fount problem it will be fixed

**Comment by Rudolf-Barbu** [comment]
Please try v1.5.5

**Comment by LukasRada** [comment]
Still getting same error:
![image](https://user-images.githubusercontent.com/7394177/86512907-22bb4180-be06-11ea-8778-ab5593bc290a.png)

**Comment by Rudolf-Barbu** [comment]
> Still getting same error:
> ![image](https://user-images.githubusercontent.com/7394177/86512907-22bb4180-be06-11ea-8778-ab5593bc290a.png)

I working on it. That was adresed to Bad3r

**Comment by LukasRada** [comment]
Oh, I see.

**Comment by Yadasko** [comment]
Having the same issue, but not on an ARM server.
[lshw.txt](https://github.com/B-Software/Ward/files/4944025/lshw.txt)

Using Ward 1.6.0, and I tried with the released JAR and by building it from sources.

**Comment by Rudolf-Barbu** [comment]
> Having the same issue, but not on an ARM server.
> [lshw.txt](https://github.com/B-Software/Ward/files/4944025/lshw.txt)
> 
> Using Ward 1.6.0, and I tried with the released JAR and by building it from sources.

Make sure you have dmidecode installed. And, please, try run project with administrative rights (With sudo on ubuntu, for example.) , this is matter for project due it need to get data from dmidecode.

**Comment by Yadasko** [comment]
Just installed dmidecode. It seems the virtualization system my server uses  (OpenVZ) is just not compatible with dmidecode, as /dev/mem is missing, which could explains the `org.bsoftware.ward.exceptions.CantGetPhysicalMemoryArrayException` stack trace.

```bash
~> sudo dmidecode
# dmidecode 3.2
Scanning /dev/mem for entry point.
/dev/mem: No such file or directory
```

That's a shame, I was really loving the look of Ward! 
Anyway, thank you for the help, good luck.

**Comment by Rudolf-Barbu** [comment]
> Just installed dmidecode. It seems the virtualization system my server uses (OpenVZ) is just not compatible with dmidecode, as /dev/mem is missing, which could explains the `org.bsoftware.ward.exceptions.CantGetPhysicalMemoryArrayException` stack trace.
> 
> ```shell
> ~> sudo dmidecode
> # dmidecode 3.2
> Scanning /dev/mem for entry point.
> /dev/mem: No such file or directory
> ```
> 
> That's a shame, I was really loving the look of Ward!
> Anyway, thank you for the help, good luck.

I will refactor this for the next release. It will just show other info in case when dmidecode is unavailable. Or just empty space.

**Comment by Rudolf-Barbu** [comment]
> When settings name (odroid) and port to 4444 on intro screen, error page appeared.
> ![image](https://user-images.githubusercontent.com/7394177/86495478-d6c2bb00-bd79-11ea-8a72-3a9ec316414a.png)
> 
> The device is Odroid-HC2.
> Here is info about HW.
> [lshw.txt](https://github.com/B-Software/Ward/files/4871322/lshw.txt)
> 
> Can I do something to resolve the issue?



> > Just installed dmidecode. It seems the virtualization system my server uses (OpenVZ) is just not compatible with dmidecode, as /dev/mem is missing, which could explains the `org.bsoftware.ward.exceptions.CantGetPhysicalMemoryArrayException` stack trace.
> > ```shell
> > ~> sudo dmidecode
> > # dmidecode 3.2
> > Scanning /dev/mem for entry point.
> > /dev/mem: No such file or directory
> > ```
> > 
> > 
> > That's a shame, I was really loving the look of Ward!
> > Anyway, thank you for the help, good luck.
> 
> I will refactor this for the next release. It will just show other info in case when dmidecode is unavailable. Or just empty space.

Guys, please try v1.7.0 and let me know if now it's just fine for you.

**Comment by LukasRada** [comment]
Yes! It works. Thank you for this awesome dashboard.
![image](https://user-images.githubusercontent.com/7394177/87960067-15fc4600-cab4-11ea-8323-ba268c55b52b.png)

**Comment by Yadasko** [comment]
Works like a charm.

Thank you for your help, and how quickly you fixed the problem.

Cheers!
