### ISSUE TITLE
Error on visiting the page.

### ISSUE THREAD

**Issue by BenitzCoding** [B-Software/Ward#44]
I managed to install and load and start it, but when I go to the page, I get an error.

I don't understand this, how do I fix it?
```
root@admin:~/ward# docker run --rm -it --name ward -p 4000:4000 -p 443:443 --privileged ward

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.0)

2021-07-23 07:17:24.521  INFO 1 --- [           main] org.bsoftware.ward.Ward                  : Starting Ward v1.8.8 using Java 1.8.0_212 on 8e5ec7d32959 with PID 1 (/ward.jar started by root in /)
2021-07-23 07:17:24.526  INFO 1 --- [           main] org.bsoftware.ward.Ward                  : No active profile set, falling back to default profiles: default
2021-07-23 07:17:25.809  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 4000 (http)
2021-07-23 07:17:25.822  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-07-23 07:17:25.822  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.39]
2021-07-23 07:17:25.876  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-07-23 07:17:25.877  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1259 ms
2021-07-23 07:17:26.164  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-07-23 07:17:26.279  INFO 1 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page template: index
2021-07-23 07:17:26.506  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 4000 (http) with context path ''
2021-07-23 07:17:26.516  INFO 1 --- [           main] org.bsoftware.ward.Ward                  : Started Ward in 2.443 seconds (JVM running for 2.957)


# When visiting the page.


2021-07-23 07:17:31.134  INFO 1 --- [nio-4000-exec-1] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x030xcd0x8a0xd60x8c0x880xb00x950xf50xba0x900xa50xe80xf90xcd0x860xe82D0xa00x140xf90x900x8e0xab0xe30xa2"0x850xc00xc3U&]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:417) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]

2021-07-23 07:17:31.134  INFO 1 --- [nio-4000-exec-2] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x030x830x08\vo}A0x0ac(0x1e0xfd0x0a0x1el20x040xfe0xe40xae0xb40x0a>E0xe2O;0x0b0xa80x800xb10x10]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:417) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.39.jar!/:9.0.39]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
```

**Comment by BenitzCoding** [comment]
@Andrew5569 Can you help?

**Comment by ItzMiracleOwO** [comment]
Try `docker run --name ward -p 8080:4000 -p 8000:8000 --privileged ward` and use port 800 as application port and see if u are redirected to localhost:8000 from the setup page (localhost:8080)

**Comment by ItzMiracleOwO** [comment]
@BenitzCoding are u there?

**Comment by BenitzCoding** [comment]
I'm sorry but my VPS expired so I can't really do that. Sorry for the delay.
